baseURL = 'https://andy.mehalick.com/'
languageCode = 'en-us'
title = 'Andy Mehalick'
theme = 'hello-friend'

[permalinks]
  posts = "/:year/:month/:day/:title/"

[params]
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Andy Mehalick"

    [languages.en.params.logo]
      logoText = "andy mehalick"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"
     